version: '3.2'

services:
  ftp:
    image: registry.netresearch.de/docker/ftp
    build: .
    environment:
      - USERS=foo:tGpvcxMKCEcEP8d9lMfnQ3bQcdLj6tFl;bar:ji7U9U6Wh6TA3ymuL6IJjeqxM8Qkcs46
    volumes:
      - "data:/home"
    ports:
      - "20:20"
      - "21:21"
      - "10090-10100:10090-10100"
volumes:
  data: