version: '3.2'

services:
  ftp:
    image: registry.netresearch.de/docker/ftp
    build: .
    environment:
      - USER=foo
      - PASSWORD=bar
    volumes:
      - "./data:/home"
    ports:
      - "20:20"
      - "21:21"
      - "10090-10100:10090-10100"