---

#####################################################################################
resources:

# Git
- name:                         git-netresearch-ftp
  type:                         git
  icon:                         git
  source:
    uri:                        https://git.netresearch.de/docker/ftp.git
    username:                   ((GIT.NETRESEARCH_USER))
    password:                   ((GIT.NETRESEARCH_PASSWORD))

# Docker
- name:                         docker-image-netresearch-ftp
  type:                         docker-image
  icon:                         docker
  check_every:                  10m
  source:
    repository:                 ghcr.io/netresearch/docker-ftp-server
    username:                   ((GIT.NETRESEARCH_USER))
    password:                   ((GIT.NETRESEARCH_PASSWORD))

# Other
- name:                         notification-slack
  type:                         slack-notification
  icon:                         slack
  check_every:                  10m
  source:
    url:                        ((MSG.URL_NR))


#####################################################################################
resource_types:
- name:                         slack-notification
  type:                         docker-image
  source:
    repository:                 arbourd/concourse-slack-alert-resource
    tag:                        latest


#####################################################################################
jobs:
- name:                         job-build-image
  build_logs_to_retain:         10
  max_in_flight:                1
  serial:                       true
  plan:
  - get:                        git-netresearch-ftp
    trigger:                    true
    params:
      depth:                    1
  - put:                        docker-image-netresearch-ftp
    params:
      build:                    git-netresearch-ftp
      build_args:
        BUILDKIT_INLINE_CACHE:  "1"
      cache:                    true
      cache_from:
        - ghcr.io/netresearch/docker-ftp-server:latest
  on_success:
    put:                        notification-slack
    params:
      alert_type:               success
  on_failure:
    put:                        notification-slack
    params:
      alert_type:               failed
  on_abort:
    put:                        notification-slack
    params:
      alert_type:               aborted

