resources:
- name: trigger-every-day
  type: time
  source:
    interval: 1d
- name: git-netresearch-ftp
  type: git
  source:
    private_key: ((GIT_NETRESEARCH_AUTH_KEY))
    uri:  git@git.netresearch.de:docker/ftp.git
    branch: master
- name: docker-image-netresearch-ftp
  type: docker-image
  source:
    repository: registry.netresearch.de/docker/ftp
    username: ((GITLAB_NETRESEARCH_USER))
    password: ((GITLAB_NETRESEARCH_USER_TOKEN))
jobs:
- name: job-build-image
  build_logs_to_retain: 5
  plan:
  - get: trigger-every-day
    trigger: true
  - get: git-netresearch-ftp
    trigger: true
    params:
      depth: 1
  - put: docker-image-netresearch-ftp
    params:
      build: git-netresearch-ftp